version: '3.8'

volumes:
  postgres-data-personas:
  postgres-data-cuentas:

networks:
  devsu-network:
    driver: bridge

services:
  db-personas:
    image: postgres:latest
    container_name: db-personas
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: personasdb
    ports:
      - "15432:5432"
    networks:
      - devsu-network
    volumes:
      - postgres-data-personas:/var/lib/postgresql/data

  db-cuentas:
    image: postgres:latest
    container_name: db-cuentas
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cuentasdb
    ports:
      - "25432:5432"
    networks:
      - devsu-network
    volumes:
      - postgres-data-cuentas:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - devsu-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - devsu-network
